// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MapperIntegration.Data.Models
{
    public partial class ProductSpec
    {
        public ProductSpec()
        {
            ShoppingCarts = new HashSet<ShoppingCart>();
        }

        public int Id { get; set; }
        public string ProductNo { get; set; }
        public string Size { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public decimal DeliveryFee { get; set; }
        public bool IsDiscounted { get; set; }
        public bool IsNew { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTimeOffset ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Product ProductNoNavigation { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}