// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MapperIntegration.Data.Models
{
    public partial class ProductImage
    {
        public int Id { get; set; }
        public string ProductNo { get; set; }
        public string Url { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTimeOffset ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Product ProductNoNavigation { get; set; }
    }
}