// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MapperIntegration.Data.Models
{
    public partial class ShoppingCart
    {
        public int Id { get; set; }
        public int ProductSpecId { get; set; }
        public int Qty { get; set; }
        public string Owner { get; set; }

        public virtual ProductSpec ProductSpec { get; set; }
    }
}